services:

  postgres:

    image: postgres:16

    container_name: tinyurl-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: tinyurl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:

    image: redis:7-alpine

    container_name: tinyurl-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      [
        "redis-server",
        "--appendonly",
        "yes"
      ]

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:

    build:
      context: .

    container_name: tinyurl-api

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

volumes:

  postgres_data:

  redis_data: