name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:

  test:

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:17

        env:
          POSTGRES_DB: tinyurl
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:8

        ports:
          - 6379:6379

        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      APP_ENV: test

      SERVER_PORT: 8080

      BASE_URL: http://localhost:8080

      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: tinyurl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      REDIS_HOST: localhost
      REDIS_PORT: 6379

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Download Dependencies
        run: go mod download

      - name: Verify Formatting
        run: |
          test -z "$(gofmt -l .)"

      - name: Run Vet
        run: go vet ./...

      - name: Run Unit Tests
        run: |
          go test ./... \
          -coverprofile=coverage.out \
          -covermode=atomic

      - name: Coverage Report
        run: |
          go tool cover -func=coverage.out

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

      - name: Build API
        run: go build -o tinyurl ./cmd/api

      - name: Build Migration Binary
        run: go build -o migrate ./cmd/migrate