name: Security Scan

on:

  push:
    branches:
      - main

  pull_request:

jobs:

  gosec:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.26.4"

      - name: Install Dependencies
        run: go mod download

      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: ./...

  trivy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .